services:
  gemini-proxy:
    image: nezhar/gemini-proxy:${GEMINI_CONTAINER_VERSION:-latest}
    build:
      context: ./gemini-proxy
      dockerfile: Dockerfile

  gemini-datasette:
    image: nezhar/gemini-datasette:${GEMINI_CONTAINER_VERSION:-latest}
    build:
      context: ./gemini-datasette
      dockerfile: Dockerfile

  gemini-cli:
    image: nezhar/gemini-container:${GEMINI_CONTAINER_VERSION:-latest}
    build:
      context: ./gemini-cli
      dockerfile: Dockerfile
